= Централизованная система оценки результатов диагностики электрооборудования энергосистемы

== Бизнес-контекст

Для поддержания надежной работы энергосистемы, требуется проводить своевременную диагностику электрооборудования, для выявления дефектов на ранней стадии развития. Компания обладает разнообразным парком различных диагностических приборов, часть из которых имеет возможность подключения к компьютеру. На данный момент в компании имеется много различного уровня прикладных программ, которые настроены на работу только с конкретным прибором. Необходимо разработать централизованную систему сбора и обработки результатов диагностики электрооборудования.

Разработанная система должна выполнять следующие требования:

* система должна быть модульной;
* рассчитана на работу с измерительными приборами, используемыми в компании;
* легко интегрироваться с новыми измерительными приборами;
* производить многостороннюю оценку результатов диагностики с выдачей рекомендации по дальнейшему обслуживанию и сроков проведения испытаний электрооборудования;
* осуществлять планирование графиков испытаний;
* интегрирована с существующими используемыми в компании системами;
* должна автоматически формироваться отчетная документация;
* постоянный сбор действий пользователя.

== Бизнес-драйверы

* автоматическая система обработки результатов диагностики на основании различных видов измерений;
* повышение надежности энергоснабжения;
* сокращение времени, затрачиваемого на создание отчетной документации, графиков диагностики и прочее.

== Бизнес-цель

Создание единой централизованной системы диагностики электрооборудования, которая будет востребована в компаниях занимающихся диагностикой электрооборудования.

== Стейкхолдеры и их потребности

_Электромонтер_ - внесение результатов электрических измерений в программу вручную или при помощи подключения прибора к компьютеру.

_Инженер по испытаниям_ - обработка результатов измерений при помощи системы, формирование окончательного результата оценки состояния электрооборудования, формирование предварительной версии протокола по результатам.

_Начальник службы диагностики_ - утверждение результатов диагностики, отчетной документации по результатам испытаний. Формирование планов диагностики электрооборудования.

_Главный инженере_ - контроль и наблюдение за проведением диагностики электрооборудования. Утверждение планов диагностики электрооборудования.

_Администратор_ - сотрудник компании, выполняющий удаленную настройку системы по требованию пользователя.

_Работник службы поддержки_ - помощь при работе с системой, обучение пользователей.

== Функциональные требования

1. Регистрация пользователей в системе:

* включение пользователей в соответствующую группу ActiveDirectory;
* исключение пользователей из соответствующей группы ActiveDirectory.

2. Внесение результатов измерений/диагностики электрооборудования в систему:

* внесение показаний вручную;
* подключение прибора к компьютеру для автоматического считывания данных;
* подключение компьютера электротехнической лаборатории, хранящей данные электрических измерений к системе, для синхронизации.

3. Оценку результатов измерений для формирования заключения о состоянии оборудования:

* оценка результатов измерений при помощи нейросети;
* формирование заключения по результатам измерений.

4. Формирование отчетов по результатам диагностики

* согласование результатов диагностики;
* формирование протоколов по результатам испытаний;
* формирование месячных, годовых, многолетних планов проведения измерений электрооборудования.

== Атрибуты качества

1. Масштабируемость

* система может работать по управлениями система Windows, Linux;
* система должна быть рассчитана на одновременную работу 1000 пользователей;
* система должна иметь возможность быть развернута как на сервере компании так и на стационарном компьютере;
* доступ к системе должен осуществляться с рабочего места сотрудника компании, посредством браузера Google Chrome;
* иметь портативную версию для установки на компьютер электролаборатории с возможностью последующей синхронизацией данных с централизованной системой.

2. Доступность

* допускается перерыв в работе системы не более 1 часа в течение одной недели в не рабочее время для администрирования, технического обслуживания.

3. Производительность

* время обработки запросов пользователя не должна превышать 1 минуту;
* время поиска оборудования, не должна превышать 2 сек;
* время анализа результатов диагностики электрооборудования при помощи нейросети, не должно превышать 30 сек.

4. Безопасность

* установлена в корпоративной сети компании, внешний доступ к системе отсутствует;
* регистрация пользователей а системе должна осуществляться через ActiveDirectory, отнесением пользователя к соответствующей группе;
* ролевая модель для работы с системой (начальник службы диагностики, инженер по испытаниям и др.);
* централизованная система хранения данных.

== Контекстная схема системы

image::Images/ContextScheme.svg[]

== Диаграмма контейнеров

image::Images/ContainerScheme.svg[]

== Диаграмма развертывания

image::Images/DeploymentScheme.svg[]

== Диаграмма последовательностей

=== Регистрация пользователя в системе

[plantuml, format="png", id="first"]
----
actor Администратор
participant ActiveDirectory
participant СервисАвторизации
database DB

Администратор -> ActiveDirectory : Добавление пользовател\nВнесение в группу AD
ActiveDirectory -> Администратор : Ok
СервисАвторизации -> ActiveDirectory : Получение списка пользователей
СервисАвторизации -> СервисАвторизации : Обновление данных пользователей
СервисАвторизации -> DB : Сохранение данных пользователей
DB -> СервисАвторизации : Ok
----

=== Внесение результатов измерений/диагностики электрооборудования

//[plantuml, format="png", id="second"]
//----
```mermaid
sequenceDiagram

actor Электромонтер
participant ПорталВнесенияДанных
participant СервисАвторизации
participant APIGateway
queue MessageBroker
participant СервисВнесенияДанных
database DB
 
Электромонтер -> ПорталВнесенияДанных : Ввод учетных данных
ПорталВнесенияДанных -> СервисАвторизации : Проверка данных пользователя
СервисАвторизации -> ПорталВнесенияДанных : Авторизация пользователя
ПорталВнесенияДанных -> Электромонтер : Список оборудования
Электромонтер -> ПорталВнесенияДанных : Выбор оборудования\nВнесение данных
ПорталВнесенияДанных -> APIGateway : Запрос на вставку данных
APIGateway -> APIGateway : Проверка данных
APIGateway -> MessageBroker : Отправка данных
MessageBroker -> APIGateway: Ok
APIGateway -> Электромонтер: Ok
MessageBroker -> СервисВнесенияДанных : Отправка данных
СервисВнесенияДанных -> СервисВнесенияДанных : Валидация данных
СервисВнесенияДанных -> СервисВнесенияДанных : Обработка данных, расчет параметров
СервисВнесенияДанных -> DB : Сохранение данных
DB -> СервисВнесенияДанных : Ок
СервисВнесенияДанных -> MessageBroker : Ok
```
//----

=== Оценку результатов измерений

//[plantuml, format="png", id="third"]
//----
```mermaid
sequenceDiagram
actor Инженер
participant ПорталОбработкиРезультатов
participant СервисАвторизации
participant APIGateway
queue MessageBroker
participant СервисОбработкиРезультатов
participant СервисИНС
database DB

Инженер -> ПорталОбработкиРезультатов : Ввод учетных данных
ПорталОбработкиРезультатов -> СервисАвторизации : Проверка данных пользователя
СервисАвторизации -> ПорталОбработкиРезультатов : Авторизация пользователя
ПорталОбработкиРезультатов -> Инженер : Список оборудования
Инженер -> ПорталОбработкиРезультатов : Выбор оборудования
ПорталОбработкиРезультатов -> APIGateway : Запрос на обработку результатов измерений
APIGateway -> APIGateway : Проверка данных
APIGateway -> MessageBroker : Отправка данных
MessageBroker -> APIGateway: Ok
APIGateway -> Инженер: Ok
APIGateway -> СервисОбработкиРезультатов : Запрос на обработку данных
СервисОбработкиРезультатов -> DB : Получение данных по оборудованию
DB -> СервисОбработкиРезультатов : Результаты измерений
СервисОбработкиРезультатов -> СервисОбработкиРезультатов : Подготовка данных для ИНС
СервисОбработкиРезультатов -> СервисИНС : Обработка результатов
СервисИНС -> СервисОбработкиРезультатов : Заключение о состонии оборудования
СервисОбработкиРезультатов -> DB : Сохранение результатов диагностики
DB -> СервисОбработкиРезультатов : Ok
```
//----

=== Формирование отчетов по результатам диагностики

//[plantuml, format="png", id="fourth"]
//----
```mermaid
sequenceDiagram

actor Начальник
participant ПорталОтчетности
participant СервисАвторизации
participant APIGateway
queue MessageBroker
participant СервисОтчетности
database DB

Начальник -> ПорталОтчетности : Ввод учетных данных
ПорталОтчетности -> СервисАвторизации : Проверка данных пользователя
СервисАвторизации -> ПорталОтчетности : Авторизация пользователя
ПорталОтчетности -> Начальник : Список оборудования
Начальник -> ПорталОтчетности : Выбор оборудования
ПорталОтчетности -> APIGateway : Запрос на формирование отчета
APIGateway -> APIGateway : Проверка данных
APIGateway -> MessageBroker : Отправка данных
MessageBroker -> APIGateway: Ok
MessageBroker -> СервисОтчетности : Запрос на формирование протокола
СервисОтчетности -> DB : Запрос на получение данных для формирования отчета
DB -> СервисОтчетности : Данные для формирвоания протокола
СервисОтчетности -> СервисОтчетности : Подготовка данных для формирования отчета
СервисОтчетности -> СервисОтчетности : Формирвоание отчета
СервисОтчетности -> MessageBroker : Ok
СервисОтчетности -> MessageBroker : Отчет
MessageBroker -> APIGateway : Отчет
APIGateway -> MessageBroker : Ok
APIGateway -> ПорталОтчетности : Отчет
ПорталОтчетности -> Начальник : Отчет
```
//----

== Лог архитектурных решений