= Централизованная система оценки результатов диагностики электрооборудования энергосистемы

== Бизнес-контекст

Для поддержания надежной работы энергосистемы, требуется проводить своевременную диагностику электрооборудования, для выявления дефектов на ранней стадии развития. Компания обладает разнообразным парком различных диагностических приборов, часть из которых имеет возможность подключения к компьютеру. На данный момент в компании имеется много различного уровня прикладных программ, которые настроены на работу только с конкретным прибором. Необходимо разработать централизованную систему сбора и обработки результатов диагностики электрооборудования.

Разработанная система должна выполнять следующие требования:

* установлена в корпоративной сети компании, внешний доступ к системе отсутствует;
* регистрация пользователей а системе должна осуществляться через ActiveDirectory, отнесением пользователя к соответствующей группе;
* допускается перерыв в работе системы не более 1 часа в течение одной недели для администрирования, технического обслуживания;
* ролевая модель для работы с системой (начальник службы диагностики, инженер по испытаниям и др.);
* доступ к системе должен осуществляться с рабочего места сотрудника компании, посредством браузера Google Chrome;
* время обработки запросов пользователя не должна превышать 1 минуту;
* централизованная система хранения данных;
* система должна быть модульной;
* рассчитана на работу с измерительными приборами, используемыми в компании;
* легко интегрироваться с новыми измерительными приборами;
* производить многостороннюю оценку результатов диагностики с выдачей рекомендации по дальнейшему обслуживанию и сроков проведения испытаний электрооборудования;
* осуществлять планирование графиков испытаний;
* интегрирована с существующими используемыми в компании системами;
* должна автоматически формироваться отчетная документация.

Дополнительные требования:

* система может работать по управлениями система Windows, Linux;
* постоянный сбор действий пользователя;
* иметь портативную версию для установки на компьютер электролаборатории с возможностью последующей синхронизацией данных с централизованной системой.

== Бизнес-драйверы

* автоматическая система обработки результатов диагностики на основании различных видов измерений;
* повышение надежности энергоснабжения;
* сокращение времени, затрачиваемого на создание отчетной документации, графиков диагностики и прочее.

== Бизнес-цель

Создание единой централизованной системы диагностики электрооборудования, которая будет востребована в компаниях занимающихся диагностикой электрооборудования.

== Стейкхолдеры и их потребности

_Электромонтер_ - внесение результатов электрических измерений в программу вручную или при помощи подключения прибора к компьютеру.

_Инженер по испытаниям_ - обработка результатов измерений при помощи системы, формирование окончательного результата оценки состояния электрооборудования, формирование предварительной версии протокола по результатам.

_Начальник службы диагностики_ - утверждение результатов диагностики, отчетной документации по результатам испытаний. Формирование планов диагностики электрооборудования.

_Главный инженере_ - контроль и наблюдение за проведением диагностики электрооборудования. Утверждение планов диагностики электрооборудования.

_Администратор_ - сотрудник компании, выполняющий удаленную настройку системы по требованию пользователя.

_Работник службы поддержки_ - помощь при работе с системой, обучение пользователей.


